### ISSUE TITLE
App builds in Xcode 14.3 beta fail with Use of undeclared identifier '_PTHREAD_MUTEX_SIG_init'

### ISSUE THREAD

**Issue by tiwoc** [bugsnag/bugsnag-cocoa#1523]
### Describe the bug
iOS app fails to build in Xcode 14.3 beta (14E5197f) with the following error in `BugsnagThread.m`:
> Use of undeclared identifier '_PTHREAD_MUTEX_SIG_init'

<img width="775" alt="Screenshot 2023-02-20 at 11 25 20" src="https://user-images.githubusercontent.com/1260821/220079796-92b88a94-753b-4aa8-b87e-1546ca3b97b8.png">

### Steps to reproduce
1. Build app that includes the BugSnag SDK
2. See error

This _doesn't_ repro in the latest stable version of Xcode (14.2).

Please let me know if you can't easily repro in Xcode 14.3 beta. I can set up a minimal reproducing example in that case.

### Environment
* Bugsnag version: 6.25.2 via SPM
* CocoaPods version: -
* Carthage version (if any): -
* iOS/tvOS/macOS version(s): building for iOS 16.4 on macOS 13.2.1
* Simulator or physical device: iPhone 14 Pro simulator
* Xcode version: 14.3 beta (14E5197f)
* Swift version (if applicable): –

**Comment by luke-belton** [comment]
Hi @tiwoc - thanks for raising this. We are investigating and will keep this thread updated with our progress 👍

**Comment by luke-belton** [comment]
Hi @tiwoc - so far in our testing we've been unable to reproduce this issue. Would you be able to share any more details, or better still a cut-down reproduction example that demonstrates the issue?

**Comment by tiwoc** [comment]
I re-tested with Xcode 14.3 beta 2 (14E5207e) and couldn't reproduce the build failure anymore, but since you ran your tests before that version was released, you must have used the first beta. Interesting 🤔 Maybe it was just a transient error due to some caching within Xcode's build system?

Anyhow, I'm not seeing the failure anymore. Thanks for taking a look, and sorry for the trouble!
